name: Firebase Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Kodu çek
        uses: actions/checkout@v3

      - name: Node.js kur
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Bağımlılıkları yükle
        run: npm install

      - name: Uygulamayı derle
        run: npm run build

      - name: Firebase CLI yükle
        run: npm install -g firebase-tools

      - name: Firebase Deploy
        run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
