name: Firebase Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Firebase CLI Kur
        run: npm install -g firebase-tools
      - name: Firebase Deploy
        run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
